### ISSUE TITLE
Add security to PTM backend

### ISSUE THREAD

**Issue by lgblaumeiser** [lgblaumeiser/ProjectTimeManager#58]
Subtasks:
- [x] Introduce concept of a user to the business model #107
- [x] Change user reference in Bookings to a user object id #108
- [x] Introduce user concept to Activities #109
- [x] Add register user rest endpoint #110
- [x] Change user reference back to username in Booking and Activity and make username a unique thing #125
- [x] Introduce basic authentication mechanism into app #127 
- [x] Make Booking rest endpoint user and auth aware #113
- [x] Make Activity rest endpoint auth and user aware #114
- [x] Make analysis rest endpoint user and auth aware #115
- [x] Make service rest endpoints user and auth aware #116
- [x] Make html access user and auth aware #117
- [x] Introduce user concept into cli #118
- [x] Add mechanism to store user/password for cli #111 
- [x] Add change password rest endpoint #120
- [x] Add delete user data rest endpoint #112
